apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermarket-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermarket-app
  template:
    metadata:
      labels:
        app: supermarket-app
    spec:
      containers:
        - name: app
          image: beatalam/supermarket-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password
            - name: DB_HOST
              value: mongo-service
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: supermarket
---
apiVersion: v1
kind: Service
metadata:
  name: supermarket-service
spec:
  type: NodePort
  selector:
    app: supermarket-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
